<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>MyOnOff.DesktopController</AssemblyName>
    <RootNamespace>MyOnOff.DesktopController</RootNamespace>
    <ApplicationIcon>Assets\MyOnOff.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyOnOff.Protocol\MyOnOff.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\MyOnOff.ico" />
  </ItemGroup>
</Project>
